export const RECIPE_NAME_MINLENGTH = 3;
export const RECIPE_NAME_MAXLENGTH = 80;
export const RECIPE_DESCRIPTION_MINLENGTH = 15;
export const RECIPE_DESCRIPTION_MAXLENGTH = 255;
export const INGREDIENTS_MIN = 2;
